---
title: "AfricaNotes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Working with layered data
```{r}

library(sp)
library(raster)
library(rgdal)

# Create a function that can act on all layers of a raster, essentially a wrapper for which.min()
maj.class <- function(x) { as.numeric( names( which.min( table(x) ) ) ) }

# create 4 rasters of the same size
r1 <- r2 <- r3 <- r4 <- raster(nrows=20, ncols=50)

# generate random raster data
r1[] <- round(runif(ncell(r1),0,2),0)
r2[] <- runif(ncell(r2),1,4)
r3[] <- runif(ncell(r3),2,6)
r4[] <- runif(ncell(r4),4,18)

# create a RasterStack
r <- stack(r1,r2,r3,r4)

mclass <- calc(r, maj.class)
plot(mclass) 
```

```{r}
rsl <- calc(r, sum)
plot(rsl)
```

## Working with CHIRPS files
```{r}

# Gather all the data files into a list
rasterlist1 <-  list.files('TIF', full.names=TRUE)

# create a sigle raster from the list
mRaster <-stack(rasterlist1)

# Set the min and Max values
mRaster <- setMinMax(mRaster)

# Function to set values below 0 to NA
fun <- function(x) { x[x<0] <-NA; return(x)}

rc2 <- calc(mRaster, fun)

# create histograms (for each layer of the RasterStack)
hist(rc2, main="Distribution Rainfall values",  col= "brown", maxpixels=22000000)
```

```{r}
# calc into a Raster Layer
rc3 <- calc(rc2, sum)

# plot the map (SUM of rainfall values from the data files)
plot(rc3)
```